[[keyboard.bindings]]
key = 'B'
mods = 'Command'
chars = "\u0001"

# disable new tab/window
[[keyboard.bindings]]
key = "T"
mods = "Command"
chars = "\u0000"

[[keyboard.bindings]]
key = "N"
mods = "Command"
chars = ""

# disable closing window, keep quit'ing
[[keyboard.bindings]]
key = "W"
mods = "Command"
chars = ""

# cmd hjkl -> ctrl hjkl for nav
[[keyboard.bindings]]
key = "h"
mods = "Command"
chars = "\u0008"

[[keyboard.bindings]]
key = "j"
mods = "Command"
chars = "\u000a"

[[keyboard.bindings]]
key = "k"
mods = "Command"
chars = "\u000b"

[[keyboard.bindings]]
key = "l"
mods = "Command"
chars = "\u000c"

