[general]
import = [
    # "~/.config/alacritty/themes/themes/catppuccin_mocha.toml",
    "~/.config/alacritty/themes/themes/ubuntu.toml",
    "~/.config/alacritty/keybindings/tmux-nvim.toml",
    "~/.config/alacritty/keybindings/term-nav.toml"
]

[font]
size = 12  # TODO(jd): make template
normal = { family = "MesloLGMNerdFontMono", style = "Regular" }
# normal = { family = "DroidSansMNerdFontMono", style = "Regular" }

[window]
option_as_alt = "Both"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"
